language: python3
dist: xenial
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=denov
  # REGISTRY_PASS travis encrypt REGISTRY_PASS=####### --add env.global
install:
- pip3 install Flask --user
- pip3 install redis --user
- pip3 install requests --user
- docker run -d --rm --name redis --network="host" redis:4-alpine redis-server --requirepass testpass
- ./app/test_counter.py </dev/null &>/dev/null &
script:
- bash test.sh
before_deploy:
- docker build -t denov/webpage-counter:latest .
- docker tag denov/webpage-counter:latest denov/webpage-counter:${TRAVIS_TAG}
- docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASS}"
deploy:
  provider: script
  script: docker push denov/webpage-counter:${TRAVIS_TAG}
  on:
    tags: true